adding intentional failure in the workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -10,5 +10,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
+      - name: Intentional Failure
+        run: |
+            echo "This step is designed to fail."
+            exit 1
       - name: Say Goodbye
         run: echo "Goodbye, World!"
